config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
    @files = Dir.glob("*")
    username = "rohitvemuri"
    @folder_name = "Desktop/PokemonEmeraldWalkthroughs"
    directory_path = File.expand_path("~#{username}/#{@folder_name}")
    if File.directory?(directory_path)
      @files1 = Dir.entries(directory_path).reject { |file| file == "." || file == ".." }
    else
      @error_message = "Directory not found: #{directory_path}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
It was nice having you here.</p>

<h1> Go to the <%= link_to "hello page", say_hello_path %> </h1>

<h1> Time in one hour: <%= 5.hour.from_now.localtime %> </h1> 

<p> <% @files.each do |file| %>
    file name is:  <ol> <%= file %> </ol>
 <% end %> </p>

 <% if @error_message %>
 <p><%= @error_message %></p>
<% else %>
 <h1>Files in <%= @folder_name %>:</h1>
 <ul>
   <% @files1.each do |file| %>
     <li><%= file %></li>
   <% end %>
 </ul>
<% end %>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<h1> It is now <%= @time %> </h1>

<h1> Time to say <%= link_to "Goodbye", say_goodbye_path %> </h1>